### ISSUE TITLE
Reset e-mail field on deselect

### ISSUE THREAD

**Issue by ckleemann** [d120/pyophase#37]
On the Students add view the text in the E-Mail field should be deleted if the student deselect all newsletters. This is the same behaviour as before #7 was fixed.

**Comment by bhaettasch** [comment]
This is not a bug.

As the commit message of a4aee933485188c4d39fcbd2581cc9aa11bf7733 says, the text in the e-mail field is not send when the field has disabled state (after deselecting all newsletters). Thus there is no need to remove it later on.

**Comment by jlauinger** [comment]
In my opinion, the email text field should only be visible if at least one newsletter is selected. This makes it very clear in terms of UX that no email address is submitted, and it's a UX bug that there is a text field that does not need to be filled if no newsletters are selected. Especially because the "optional" label visually belongs to the checkboxes, not the text field.

**Comment by bhaettasch** [comment]
The email text field is visible but has disabled state - which is one of the common ways to show that a field is not needed/prevent people from filling it.

I guess the confusion results from an error during deployment, that caused the field not to be disabled. After this is fixed, do you stil think changes should be made, @jlauinger?

**Comment by jlauinger** [comment]
ok, blame myself, didn't deploy completely.

I'm with @ckleemann now. While one can do it the way currently implemented, I think it is less confusing to have the field visually out of the way instead of wondering whether the content of the disabled field are just not editable, but do will get submitted.

I could even imagine someone re-checking a newsletter, clearing his email and then uncheck again.

**Comment by bhaettasch** [comment]
OK, I see your point, so it may be worth the effort to change the things the user see, while it is definitely no problem that there is no server side logic to remove the mail adress (which can only be entered by manipulating post data).

I will change the behaviour to toggle the visibility in addition to making the field disabled, but won't delete the content of the field on client side, so that it is preserved if the user unchecks all newsletters inadvertently.

**Comment by jlauinger** [comment]
... which imho is the exact right way to do it, thanks @bhaettasch

**Comment by bhaettasch** [comment]
Make sure static files are deployed correctly, as this fix only changes the javascript file.
