### ISSUE TITLE
Make Clothing Sizes Sortable

### ISSUE THREAD

**Issue by exploide** [d120/pyophase#92]
Currently, the clothing size objects are not really sortable. This leads to a strange experience during the ordering process and on overview views.

**Comment by ckleemann** [comment]
Since 697c47e06a9606658bf1a46096a541e724841114 there is  _sortable_size_ method in the size model to support the sorting. But this method can not be used in all places to sort a number of sizes: Currently it is not possible to sort the sizes in the clothing form. Therefore another solution is needed.

Maybe adding a new field to the size model which stores the value of sortable_size method would be a solution.
